name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build_and_package:
    name: Build and Package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build  with Maven
        run: mvn -B package --file pom.xml
